
# Day 1

## Write a paragraph about something new you learned in class within the past 24 hours.

In today's class, I learned that spatio-temporal statistics is a relatively new area with few books on it. What's interesting is that our course is somewhat unique, blending spatial and temporal elements, something not typical in other universities. I was also interetisting to learn about the connection between land-grant universities and the role their statistics departments play in shaping their education systems, especially here at K-State. Plus, I was quite surprised to find out about the earthquakes in southern Kansas, which are likely linked to oil wells.

## Write a paragraph about something you are struggling to understand that was covered in class within the past 24 hours.

So far, I have not struggle in understanding the material covered in class. Everything has been clear.

## Is there anything else you would like me to be aware of?

No, there is not anything else until this moment.



